; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "CoreStation Windows Service"
#define MyAppVersion "20.25.6.1_rc3"
#define MyAppPublisher "Amulet Hotkey LTD"
#define MyAppURL "https://www.amulethotkey.com/"
#define MyAppExeName "nodeWinApp.exe"
#define MyServiceInstallScript "install.ps1"
#define MyServiceUninstallScript "remove.ps1"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=CoreStation_Management_Service
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL= https://www.amulethotkey.com/support/
DefaultDirName={autopf}\CoreStation Windows App
DisableDirPage=yes
DefaultGroupName=Amulet Hotkey
DisableProgramGroupPage=yes
CreateAppDir=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
PrivilegesRequired=admin
OutputBaseFilename=CoreStation Windows App Installer 2025.6.1_rc3
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=win64
SetupIconFile=logo.ico
AlwaysRestart=yes
MinVersion=10.0.19045

VersionInfoCompany=Amulet Hotkey
VersionInfoCopyright=© Amulet Hotkey 2025
VersionInfoDescription=CoreStation Windows Service installer
VersionInfoProductTextVersion=20.25.6.1
VersionInfoProductVersion=20.25.6.1
VersionInfoVersion=20.25.6.1
VersionInfoProductName=CoreStation Windows Service Installer

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\Users\michael.madell\Documents\CoreStationAppInstallerInno\install.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\michael.madell\Documents\CoreStationAppInstallerInno\nodeWinApp.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\michael.madell\Documents\CoreStationAppInstallerInno\remove.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\michael.madell\Documents\CoreStationAppInstallerInno\logo.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Uninstall CoreStation Windows Service"; Filename: "{uninstallexe}"; IconFilename: "{app}\logo.ico"; 


[Run]
Filename: "powershell.exe"; \
  Parameters: "-ExecutionPolicy Bypass -NoProfile -File ""{app}\{#MyServiceInstallScript}"""; \
  WorkingDir: "{app}"; \
  Flags: runhidden waituntilterminated; \
  StatusMsg: "Installing CoreStation Service..."
  
[UninstallRun]
Filename: "powershell.exe"; \
  Parameters: "-ExecutionPolicy Bypass -NoProfile -File ""{app}\{#MyServiceUninstallScript}"""; \
  WorkingDir: "{app}"; \
  Flags: runhidden waituntilterminated; \
  StatusMsg: "Uninstalling CoreStation Service..."
  
[UninstallDelete]
Type: filesandordirs; Name: "{app}"
