; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "CoreStation HX Agent"
#define MyAppVersion "20.26.3.1_rc2"
#define MyAppVersionShort "20.26.3.1"
#define MyAppPublisher "Amulet Hotkey LTD"
#define MyAppURL "https://www.amulethotkey.com/"
#define MyAppExeName "CoreStationHXAgent.exe"
#define MyServiceInstallScript "install.ps1"
#define MyServiceUninstallScript "remove.ps1"

[Setup]
AppId=CoreStation_Management_Service
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL=https://www.amulethotkey.com/support/
DefaultDirName=C:\Program Files (x86)\CoreStation HX Agent
DisableDirPage=yes
DefaultGroupName=Amulet Hotkey
DisableProgramGroupPage=yes
CreateAppDir=yes
PrivilegesRequired=admin
OutputBaseFilename=CoreStation HX Agent Installer {#MyAppVersion}
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=win64
SetupIconFile=logo.ico
AlwaysRestart=yes
MinVersion=10.0.19045

VersionInfoCompany=Amulet Hotkey
VersionInfoCopyright=© Amulet Hotkey 2025
VersionInfoDescription=CoreStation HX Agent installer
VersionInfoProductTextVersion={#MyAppVersionShort}
VersionInfoProductVersion={#MyAppVersionShort}
VersionInfoVersion={#MyAppVersionShort}
VersionInfoProductName=CoreStation HX Agent Installer

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: ".\install.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\CoreStationHXAgent.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\remove.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\logo.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Uninstall CoreStation HX Agent"; Filename: "{uninstallexe}"; IconFilename: "{app}\logo.ico"

[Run]
; Diagnostic: confirm [Run] is reached at all — check for C:\Windows\Temp\CoreStation_run.log after install
Filename: "cmd.exe"; \
  Parameters: "/c echo [Run] reached > C:\Windows\Temp\CoreStation_run.log"; \
  Flags: runhidden waituntilterminated

Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; \
  Parameters: "-ExecutionPolicy Bypass -NoProfile -File ""{app}\{#MyServiceInstallScript}"""; \
  WorkingDir: "{app}"; \
  Flags: runhidden waituntilterminated; \
  StatusMsg: "Installing CoreStation HX Agent..."

[UninstallRun]
Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; \
  Parameters: "-ExecutionPolicy Bypass -NoProfile -File ""{app}\{#MyServiceUninstallScript}"""; \
  WorkingDir: "{app}"; \
  Flags: runhidden waituntilterminated; \
  StatusMsg: "Uninstalling CoreStation HX Agent..."

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  LogFile: string;
begin
  LogFile := 'C:\Windows\Temp\CoreStation_code.log';

  if CurStep = ssInstall then
  begin
    SaveStringToFile(LogFile, '[Code] ssInstall reached' + #13#10, False);

    SaveStringToFile(LogFile, 'Extracting remove.ps1 to tmp...' + #13#10, True);
    ExtractTemporaryFile('remove.ps1');
    SaveStringToFile(LogFile, 'Extracted OK. Running remove.ps1...' + #13#10, True);

    Exec(
      ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'),
      '-ExecutionPolicy Bypass -NoProfile -File "' + ExpandConstant('{tmp}') + '\remove.ps1"',
      ExpandConstant('{tmp}'),
      SW_HIDE,
      ewWaitUntilTerminated,
      ResultCode
    );
    SaveStringToFile(LogFile, 'remove.ps1 exited with code: ' + IntToStr(ResultCode) + #13#10, True);
  end;
end;

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
